### ISSUE TITLE
problem in detecting final object boxes using only exported m2det onnx model

### ISSUE THREAD

**Issue by sbashett** [georgymironov/single_shot_detection#2]
Hello, firstly thanks for open-sourcing this wonderful and clean code for embedding different object detectors. 
I am trying to export a trained m2det model to onnx format and then do the inference by wrapping it in a tensorflow serving module. However, in the exported model only the prediction outputs of network are included by excluding the anchor box priors. These priors are needed to post-process and derive the final object boxes. I tried looking into your process of generating the prior boxes, but it seems to be tightly interlinked with the model architecture itself and this makes it necessary to always keep the source code around. Is there a way I could disregard the source code for architecture and generate the anchor boxes as a standalone script so that I could finally use only the frozen model, priors and post-processing functions to generate predictions? Thanks in advance.

**Comment by georgymironov** [comment]
Hello. Sorry for the late response.

Sadly, I believe there is no way to export everything in a single ONNX model as the standard does not support any detection related layers like PriorBox or DetectionOutput. So the best solution imo is to modify the code to pickle generated anchors boxes as a numpy object. 
And then use `decode` function from `box_coder.py` to convert the model output. Or use can just write the function yourself in numpy/tensorflow instead of pytorch as it being pretty simple.

There is also one more solution: you can export the whole model in torch jit with `--phase export-torch` flag, but that will require you to run pytorch as a backend for inference

**Comment by sbashett** [comment]
Thanks for your reply, and I did already solve the issue by saving the anchors for a specific anchor configuration as a pickle file. I pulled out the specific code for regressing the bounding boxes and scores from the network predictions. BTW,  even tried including the priors into the onnx exporter outputs and it did work but the problem, it is creating a lot of overhead while inference from the tf frozen model (since it uses a server client protocol). Later did I realize that the priors remain fixed for a specific anchor parameter config. Thanks for sharing this well written and useful repo.
